spring:
  application:
    name: tom-dubbo-consumer
server:
  port: 9091
hello:
  service:
    version: 1.0.0
dubbo:
  application:
    id: tom-dubbo-consumer-id
    name: tom-dubbo-consumer
  registry:
    protocol: zookeeper
    address: 192.168.60.214:2181
    id: tom-registry-consumer
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'